=== cssAreaGH/CSSM-XML-Schemas/902x01b1TC1-SmplSchd.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xsd:schema xmlns="urn:ccsds:schema:cssm:1.0.0" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:ccsds:schema:cssm:1.0.0" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0.0">
	<xsd:include schemaLocation="902x13m1-AbsEvnt-TimCde.xsd"/>
	<xsd:include schemaLocation="902x13m1-AbsEvnt-AbsParm.xsd"/>
	<xsd:include schemaLocation="902x12m1-SmCmnEnt-InfEntHdr.xsd"/>
	<!--********************************************************************************************************************** -->
	<!--** Simple Schedule types and elements ** -->
	<xsd:element name="simpleSchedule" type="SimpleScheduleType"/>
	<xsd:complexType name="SimpleScheduleType">
		<xsd:complexContent>
			<xsd:extension base="SrvMgtInfoEntityType"/>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:simpleType name="SimpleScheduleStatus">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="TEST"/>
			<xsd:enumeration value="PROVISIONAL"/>
			<xsd:enumeration value="OPERATIONAL"/>
			<xsd:enumeration value="OTHER"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="InclusionType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="OVERLAP_INCLUSION"/>
			<xsd:enumeration value="START_INCLUSION"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:element name="simpleScheduleHeader" type="SimpleScheduleHeaderType" substitutionGroup="srvMgtHeader"/>
	<xsd:complexType name="SimpleScheduleHeaderType">
		<xsd:complexContent>
			<xsd:extension base="SrvMgtHeaderType">
				<xsd:sequence>
					<!-- allow a list of parameters derived from AbstractParameter -->
					<xsd:element ref="abstractParameter" minOccurs="0" maxOccurs="unbounded"/>
				</xsd:sequence>
				<xsd:attribute name="status" type="SimpleScheduleStatus" use="required"/>
				<xsd:attribute name="inclusionType" type="InclusionType" use="required"/>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:element name="scheduledPackage" type="ScheduledPackageType" substitutionGroup="srvMgtData"/>
	<xsd:complexType name="ScheduledPackageType">
		<xsd:complexContent>
			<xsd:extension base="SrvMgtDataType">
				<xsd:sequence>
					<xsd:element name="servicePackageXRef" type="ServicePackageXRefType" minOccurs="0"/>
					<!-- allow a list of parameters derived from AbstractParameter -->
					<xsd:element ref="abstractParameter" minOccurs="0" maxOccurs="unbounded"/>
					<xsd:element name="scheduledActivity" type="ScheduledActivityType" maxOccurs="unbounded"/>
				</xsd:sequence>
				<xsd:attribute name="scheduledPackageId" type="xsd:ID" use="required"/>
				<xsd:attribute name="user" type="xsd:string" use="required"/>
				<xsd:attribute name="originatingRequestId" type="xsd:string"/>
				<xsd:attribute name="comment" type="xsd:string"/>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:complexType name="ScheduledActivityType">
		<xsd:sequence>
			<xsd:element name="serviceInfo" type="ServiceInfoType" maxOccurs="unbounded"/>
			<!-- allow a list of parameters derived from AbstractParameter -->
			<xsd:element ref="abstractParameter" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="scheduledActivityId" type="xsd:string" use="required"/>
		<xsd:attribute name="activityStatus" use="required">
			<xsd:simpleType>
				<xsd:restriction base="xsd:string">
					<xsd:enumeration value="COMMITTED"/>
					<xsd:enumeration value="TENTATIVE"/>
					<xsd:enumeration value="AVAILABLE"/>
					<xsd:enumeration value="UNAVAILABLE"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
		<xsd:attribute name="siteRef" type="xsd:string" use="required">
			<xsd:annotation>
				<xsd:documentation>SANA-registered value</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="apertureRef" type="xsd:string" use="required">
			<xsd:annotation>
				<xsd:documentation>SANA-registered value</xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="beginningOfActivity" type="CcsdsAsciiTimeCodeBType"/>
		<xsd:attribute name="beginningOfTrack" type="CcsdsAsciiTimeCodeBType" use="required"/>
		<xsd:attribute name="endOfTrack" type="CcsdsAsciiTimeCodeBType" use="required"/>
		<xsd:attribute name="endOfActivity" type="CcsdsAsciiTimeCodeBType"/>
		<xsd:attribute name="orbitNumber" type="xsd:nonNegativeInteger"/>
	</xsd:complexType>
	<xsd:complexType name="ServicePackageXRefType">
		<xsd:attribute name="serviceAgreementRef" type="xsd:string" use="required"/>
		<xsd:attribute name="servicePackageRef" type="xsd:string" use="required"/>
	</xsd:complexType>
	<xsd:element name="scheduledPkgAssn" substitutionGroup="srvMgtData">
		<xsd:complexType>
			<xsd:complexContent>
				<xsd:extension base="ScheduledPkgAssnType"/>
			</xsd:complexContent>
		</xsd:complexType>
	</xsd:element>
	<xsd:complexType name="ScheduledPkgAssnType">
		<xsd:complexContent>
			<xsd:extension base="SrvMgtDataType">
				<xsd:sequence>
					<xsd:element name="scheduledPackageIdRef" type="ScheduledPackageIdRefType" minOccurs="1" maxOccurs="unbounded"/>
					<xsd:element name="externalSchedPkgIdRef" type="ExternalSchedPkgIdRefType" minOccurs="0" maxOccurs="unbounded"/>
					<!-- allow a list of parameters derived from AbstractParameter -->
					<xsd:element ref="abstractParameter" minOccurs="0" maxOccurs="unbounded"/>
				</xsd:sequence>
				<xsd:attribute name="associationId" type="xsd:string" use="required"/>
				<xsd:attribute name="associationKind" type="xsd:string" use="required">
					<xsd:annotation>
						<xsd:documentation>SANA-registered value</xsd:documentation>
					</xsd:annotation>
				</xsd:attribute>
				<xsd:attribute name="comment" type="xsd:string"/>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:complexType name="ScheduledPackageIdRefType">
		<xsd:attribute name="ref" type="xsd:IDREF"/>
	</xsd:complexType>
	<xsd:complexType name="ExternalSchedPkgIdRefType">
		<xsd:attribute name="ref" type="xsd:string"/>
	</xsd:complexType>
	<xsd:simpleType name="ServiceType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="APA-AZ/EL"/>
			<xsd:enumeration value="APA-X/Y"/>
			<xsd:enumeration value="DELTADOR"/>
			<xsd:enumeration value="DOPPLER"/>
			<xsd:enumeration value="OFFLINE-TM-RECORDING"/>
			<xsd:enumeration value="OFFLINE-TM-PROVISION"/>
			<xsd:enumeration value="RF-ONLY"/>
			<xsd:enumeration value="RANGING"/>
			<xsd:enumeration value="RESERVED"/>
			<xsd:enumeration value="TBD"/>
			<xsd:enumeration value="TELECOMMAND"/>
			<xsd:enumeration value="TELEMETRY"/>
			<xsd:enumeration value="TEST"/>
			<xsd:enumeration value="UNUSED"/>
			<xsd:enumeration value="VLBI"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="FrequencyBandType">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="HF"/>
			<xsd:enumeration value="VHF"/>
			<xsd:enumeration value="UHF"/>
			<xsd:enumeration value="L"/>
			<xsd:enumeration value="S-NE"/>
			<xsd:enumeration value="S-DS"/>
			<xsd:enumeration value="C"/>
			<xsd:enumeration value="X-NE"/>
			<xsd:enumeration value="X-DS"/>
			<xsd:enumeration value="Ku"/>
			<xsd:enumeration value="K"/>
			<xsd:enumeration value="Ka-NE"/>
			<xsd:enumeration value="Ka-DS"/>
			<xsd:enumeration value="Ka-S"/>
			<xsd:enumeration value="V"/>
			<xsd:enumeration value="W"/>
			<xsd:enumeration value="mm"/>
			<xsd:enumeration value="O1"/>
			<xsd:enumeration value="O2"/>
			<xsd:enumeration value="N/A"/>
			<xsd:enumeration value="OTHER"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name="ServiceInfoType">
		<xsd:sequence>
			<!-- allow a list of parameters derived from AbstractParameter -->
			<xsd:element ref="abstractParameter" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute name="serviceType" type="ServiceType" use="required"/>
		<xsd:attribute name="frequencyBand" type="FrequencyBandType" use="required"/>
	</xsd:complexType>
</xsd:schema>

=== cssAreaGH/CSSM-XML-Schemas/Example-902x01b1TC1-SimpleSchedule.xml
<?xml version="1.0" encoding="UTF-8"?>
<simpleSchedule xmlns="urn:ccsds:schema:cssm:1.0.0"
					 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
					 xmlns:xmi="http://www.omg.org/XMI"
					 xsi:schemaLocation="urn:ccsds:schema:cssm:1.0.0 902x01b1TC1-SmplSchd.xsd" >
	<simpleScheduleHeader originatingOrganization="RKPNI"
								 generationTime="2016-307T13:46:48.247Z"
								 status="TEST"
								 inclusionType="OVERLAP_INCLUSION"
								 version="1"
								 startTime="2016-134T00:00:00.000Z"
								 endTime="2016-164T00:00:00.000Z"
								 purpose="Purpose of the schedule."
								 description="Schedule description."/>
	<scheduledPackage scheduledPackageId="EVENT-2015.190.11.41.47.243348-821429"
							user="GAIA"
							originatingRequestId ="GAIA_Dummy_Request_001">
		<servicePackageXRef serviceAgreementRef="GAIA_Routine_1.daily_TTC.nominal_definition.GAIA"
								  servicePackageRef="EVENT-2015.190.11.41.47.243348-821429"/>
		<scheduledActivity scheduledActivityId="EVENT-2015.190.11.41.47.243348-821429"
								 activityStatus="COMMITTED"
								 siteRef="MLG"
								 apertureRef="MLG"
								 beginningOfActivity="2016-134T02:47:52.000Z"
								 beginningOfTrack="2016-134T03:32:52.000Z"
								 endOfTrack="2016-134T10:10:29.000Z"
								 endOfActivity="2016-134T10:25:29.000Z">
			<serviceInfo	serviceType="TELEMETRY"
							frequencyBand="X-DS" >
			</serviceInfo>
		</scheduledActivity>
	</scheduledPackage>
	<scheduledPackage scheduledPackageId="EVENT-2015.190.10.48.15.165576-808510"
							user="LIPF"
							originatingRequestId ="LIPF_Dummy_Request_001">
		<servicePackageXRef serviceAgreementRef="Lisa_Pathfinder_1.daily_TTC.nominal_definition.LIPF"
								  servicePackageRef="EVENT-2015.190.10.48.15.165576-808510"/>
		<scheduledActivity scheduledActivityId="EVENT-2015.190.10.48.15.165576-808510"
								 activityStatus="COMMITTED"
								 siteRef="CEB"
								 apertureRef="CEB"
								 beginningOfActivity="2016-134T05:15:00.000Z"
								 beginningOfTrack="2016-134T06:00:00.000Z"
								 endOfTrack="2016-134T14:00:00.000Z"
								 endOfActivity="2016-134T14:15:00.000Z">
			<serviceInfo	serviceType="TELEMETRY"
							frequencyBand="X-DS" >
			</serviceInfo>
		</scheduledActivity>
	</scheduledPackage>
	<scheduledPackage scheduledPackageId="EVENT-2015.190.13.59.48.510482-846702"
							user="ROS"
							comment="This is an example of an optional comment for a scheduled package..."
							originatingRequestId ="ROS_Dummy_Request_001">
		<servicePackageXRef serviceAgreementRef="ROSETTA_Routine_2.Continuous_TTC.nominal_definition.ROS"
								  servicePackageRef="EVENT-2015.190.13.59.48.510482-846702"/>
		<scheduledActivity scheduledActivityId="EVENT-2015.190.13.59.48.510482-846702"
								 activityStatus="COMMITTED"
								 siteRef="NNO"
								 apertureRef="NNO"
								 beginningOfActivity="2016-134T06:36:08.000Z"
								 beginningOfTrack="2016-134T07:21:08.000Z"
								 endOfTrack="2016-134T16:05:48.000Z"
								 endOfActivity="2016-134T16:20:48.000Z">
			<serviceInfo	serviceType="TELEMETRY"
							frequencyBand="X-DS" >
			</serviceInfo>
		</scheduledActivity>
	</scheduledPackage>
	<scheduledPackage scheduledPackageId="TEST-SC1_Scheduled_Package_001"
							user="TEST-SC1"
							originatingRequestId ="TEST-SC1_Dummy_Request_001">
		<servicePackageXRef serviceAgreementRef="TEST-SC1_Service_Agreement"
								  servicePackageRef="TEST-SC1_Service_Package_001"/>
		<scheduledActivity scheduledActivityId="TEST-SC1_Schedule_Activity_001"
								 activityStatus="TENTATIVE"
								 siteRef="NNO"
								 apertureRef="NNO"
								 beginningOfActivity="2016-136T16:00:00.000Z"
								 beginningOfTrack="2016-136T17:16:30.000Z"
								 endOfTrack="2016-136T22:00:00.000Z"
								 endOfActivity="2016-136T22:30:00.000Z">
			<serviceInfo	serviceType="TELEMETRY"
							frequencyBand="X-DS" >
			</serviceInfo>
			<serviceInfo	serviceType="TELECOMMAND"
							frequencyBand="X-DS" >
			</serviceInfo>
		</scheduledActivity>
	</scheduledPackage>
	<scheduledPackage scheduledPackageId="TEST-SC2_Scheduled_Package_001"
							user="TEST-SC2"
							originatingRequestId ="TEST-SC2_Dummy_Request_001">
		<servicePackageXRef serviceAgreementRef="TEST-SC2_Service_Agreement"
								  servicePackageRef="TEST-SC2_Service_Package_001"/>
		<scheduledActivity scheduledActivityId="TEST-SC2_Schedule_Activity_001"
								 activityStatus="TENTATIVE"
								 siteRef="NNO"
								 apertureRef="NNO"
								 beginningOfActivity="2016-136T17:00:00.000Z"
								 beginningOfTrack="2016-136T17:30:00.000Z"
								 endOfTrack="2016-136T23:00:00.000Z"
								 endOfActivity="2016-136T23:30:00.000Z">
			<serviceInfo	serviceType="TELEMETRY"
							frequencyBand="X-DS" >
			</serviceInfo>
		</scheduledActivity>
	</scheduledPackage>
	<scheduledPkgAssn associationId = "Association_TEST-SC1_Schedule_Package_001_and_TEST-SC2_Schedule_Package_001"
						 associationKind = "MSPA"
						 comment = "MSPA pass on New Norcia for TEST-SC1 and TEST-SC2" >
						 <scheduledPackageIdRef ref="TEST-SC1_Scheduled_Package_001" />
						 <scheduledPackageIdRef ref="TEST-SC2_Scheduled_Package_001" />
						 <externalSchedPkgIdRef ref="This_is_an_example_of_a_reference_to_an_external_Scheduled_Package_i.e._One_that_is_not_contained_in_the_same_XML_file" />
	</scheduledPkgAssn>
	</simpleSchedule>
